# Ansible playbook ver 1
-
 name: deploy Web Application
 hosts: db_and_web_server1, db_and_web_server2 
 tasks:
  - name: Install all required dependencies
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - "epel-release"
      - "python"
      - "python-devel"
  - name: Install MySQL community repository
    yum:
      name: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
      state: present

  - include: tasks/deploy_app.yml
  - include: tasks/deploy_db.yml



























































































































































































































































































































































































































































































































































































































